branch-defaults:
  default:
    environment: sol-default-eb-env
environment-defaults:
  sol-default-eb-env:
    branch: null
    repository: null
global:
  application_name: sol-default-eb
  default_ec2_keyname: plato-kp-new
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
