version: '3.8'
services:

  # ------------------------------------------------------------------------------
  # PUBLIC

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpw
      - POSTGRES_DB=solwtf
    # No need to specify entrypoint, it's a postgres container
#    volumes:
#      - ./postgres-DEV:/var/lib/postgresql/data/
#    logging:
#      driver: "none"

  # ------------------------------------------------------------------------------
  # PRIVATE

  nginx:
    depends_on:
      - backend
      - frontend
    image: nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    # No need to specify entrypoint, it's an nginx container
    ports:
      - 80:80 #outside -> inside
#    logging:
#      driver: "none"

  frontend:
    image: frontend
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    # No need to specify entrypoint, it's an nginx container
    ports:
      - 8080:8080
#    volumes:
#      - /app/node_modules #we don't want to copy this from outside the ctr
#      - ./frontend:/app

  backend:
    image: backend
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.FAKE_PROD
      context: ./backend
    entrypoint: ["/app/scripts/boot.FAKE_PROD.sh"]
    ports:
      - 5000:5000
#    volumes:
#      - /app/target #we don't want to copy this from outside the ctr
#      - ./backend:/app

#todo for this to work need to figure out how to pass secrets in